description: >-
  Node-based Docker image with Java 11 and browsers like Firefox, Chrome, Explorer
parameters:
  tag:
    type: string
    default: 15.0.1-browsers
    description: >
      Specific variant of CircleCI's Selenium Node Image:
      https://hub.docker.com/r/cimg/node
  working-directory:
    type: string
    default: ~/project
    description: >
      Working directory for the job using this executor:
      https://circleci.com/docs/2.0/configuration-reference/#job_name
docker:
  - image: 'cimg/node:<< parameters.tag >>'
working_directory: <<parameters.working-directory>>
