description: >-
  Docker image having Java version 8, ant latest version and browsers like
  Firefox, Chrome, Explorer
parameters:
  tag:
    type: string
    default: 11-jdk-browsers
    description: >
      Specific variant of CircleCI's OpenJDK image to use:
      https://hub.docker.com/r/circleci/openjdk/tags
  working-directory:
    type: string
    default: ~/project
    description: >
      Working directory for the job using this executor:
      https://circleci.com/docs/2.0/configuration-reference/#job_name
docker:
  - image: 'circleci/openjdk:<< parameters.tag >>'
working_directory: <<parameters.working-directory>>
